//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVM.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere Person.
        /// </summary>
        public static string LV_BtnAendern_Content {
            get {
                return ResourceManager.GetString("LV_BtnAendern_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche Person.
        /// </summary>
        public static string LV_BtnLoeschen_Content {
            get {
                return ResourceManager.GetString("LV_BtnLoeschen_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Person.
        /// </summary>
        public static string LV_BtnNeu_Content {
            get {
                return ResourceManager.GetString("LV_BtnNeu_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string LV_MeiBeenden_Header {
            get {
                return ResourceManager.GetString("LV_MeiBeenden_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string LV_MeiDatei_Header {
            get {
                return ResourceManager.GetString("LV_MeiDatei_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string LV_MeiDeutsch_Header {
            get {
                return ResourceManager.GetString("LV_MeiDeutsch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        public static string LV_MeiEnglisch_Header {
            get {
                return ResourceManager.GetString("LV_MeiEnglisch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string LV_MeiSprache_Header {
            get {
                return ResourceManager.GetString("LV_MeiSprache_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum.
        /// </summary>
        public static string M_Person_Geburtsdatum {
            get {
                return ResourceManager.GetString("M_Person_Geburtsdatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht.
        /// </summary>
        public static string M_Person_Geschlecht {
            get {
                return ResourceManager.GetString("M_Person_Geschlecht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinder.
        /// </summary>
        public static string M_Person_Kinder {
            get {
                return ResourceManager.GetString("M_Person_Kinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieblingsfarbe.
        /// </summary>
        public static string M_Person_Lieblingsfarbe {
            get {
                return ResourceManager.GetString("M_Person_Lieblingsfarbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string M_Person_Nachname {
            get {
                return ResourceManager.GetString("M_Person_Nachname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verheiratet.
        /// </summary>
        public static string M_Person_Verheiratet {
            get {
                return ResourceManager.GetString("M_Person_Verheiratet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string M_Person_Vorname {
            get {
                return ResourceManager.GetString("M_Person_Vorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personendatenbank.
        /// </summary>
        public static string Title_Text {
            get {
                return ResourceManager.GetString("Title_Text", resourceCulture);
            }
        }
    }
}
